import './globals.css';

import { Inter } from 'next/font/google';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import { AuthProvider } from './contexts/authContext';
import Navbar from '@/components/Navbar';



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={""}
      >
      <AuthProvider>
        
          {children}
          <ToastContainer position="top-right" autoClose={3000} />
        </AuthProvider>
        
      </body>
    </html>
  );
}
